version: '3'
services:
  mysql:
    image: mysql
    container_name: mysql
    volumes:
      - ./datadir:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: senha
      MYSQL_ROOT_HOST: "%"
    networks:
      - minha_rede

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "80:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: senha
    networks:
      - minha_rede

  wordpress:
    image: wordpress
    container_name: wordpress
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: senha
      WORDPRESS_DB_NAME: mysql
    networks:
      - minha_rede

networks:
  minha_rede:
    